spring:
  application:
    name: deokhugam
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: jdbc:postgresql://${RDS_ENDPOINT:localhost}:${DB_PORT:5432}/${DB_NAME:discodeit}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 60000
  jpa:
    hibernate.ddl-auto: none
    defer-datasource-initialization: true
    show-sql: false
    properties.hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  sql.init:
    mode: always
    continue-on-error: false
  batch:
    job:
      enabled: false
    jdbc:
      schema: batch
      initialize-schema: never  # 자동 생성/삭제 방지

deokhugam:
  storage:
    type: ${STORAGE_TYPE:local}
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:./storage}

management:
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
    health:
      show-details: always

aws:
  accessKeyId: ${AWS_S3_ACCESS_KEY:your-access-key}
  secretKey: ${AWS_S3_SECRET_KEY:your-secret-key}
  region: ${AWS_S3_REGION:ap-northeast-2}
  s3:
    bucket: ${AWS_S3_BUCKET:your-bucket-name}
    base-url: ${AWS_S3_BASE_URL:https://your-bucket-name.s3.amazonaws.com}

naver:
  client-id: ${NAVER_CLIENT_ID:naver-client-id}
  client-secret: ${NAVER_CLIENT_SECRET:naver-client-secret}

server:
  port: 80