spring:
  application:
    name: deokhugam
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

management:
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
    health:
      show-details: always

aws:
  accessKeyId: ${AWS_S3_ACCESS_KEY:your-access-key}
  secretKey: ${AWS_S3_SECRET_KEY:your-secret-key}
  region: ${AWS_S3_REGION:ap-northeast-2}
  s3:
    bucket: ${AWS_S3_BUCKET:your-bucket-name}
    expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}
